### ISSUE TITLE
Testing authentication

### ISSUE THREAD

**Issue by orenyk** [BlakeWilliams/doorman#17]
Hi, I'm trying to write some basic acceptance tests for authentication. Signing in is fine, but I wasn't sure how to approach signing out. I'd like to log a user in during the `setup` function (i.e. `conn |> login(user)`), but using the built in `Doorman.Login.Session.login/2` method fails with

```
** (ArgumentError) session not fetched, call fetch_session/2
```

I tried calling `conn |> Plug.Conn.fetch_session |> login(user)` but that failed with:

```
** (ArgumentError) cannot fetch session without a configured session plug
```

at which point I just used `conn |> assign(:user_id, user.id)`, which did work, but makes me very uncomfortable. Do you have any suggestions about how to do this better or how to write test helpers for authentication? Thanks!

**Comment by BlakeWilliams** [comment]
I generally have the following function available in my tests:

``` elixir
  def authenticate(user \\ insert(:user)) do
    conn = build_conn()
      |> assign(:current_user, user)
    %{conn: conn, user: user}
  end
```

So I can have a setup function that returns `{:ok, authenticate}`.

I've also seen a solution where a plug is used only in the test environment that looks for an `as` parameter on each request. The value for that `as` param is a user id and then that user is set as `current_user`.

Those are the two I've seen that work well. I only use these in controller tests but if you want a more end-to-end test I suggest looking into [Hound](https://github.com/HashNuke/hound) or [Wallaby](https://github.com/keathley/wallaby).

Let me know if that helps or if you have any more questions!

**Comment by orenyk** [comment]
Thanks @BlakeWilliams, that's a good explanation. The use case I'm currently working on is writing acceptance / integration tests using Hound.

To make sure I'm understanding your comment, are you basically bypassing Doorman entirely by just assigning a current user to the `conn` directly, instead of dealing with the session? Also, is that assignment of `current_user` something you also write yourself in the actual codebase, which is why you can just basically fake it during test?

Thanks for your help!

**Comment by BlakeWilliams** [comment]
For Hound I usually have a function that runs through login manually (through hound) rather than bypass it.

> To make sure I'm understanding your comment, are you basically bypassing Doorman entirely by just assigning a current user to the conn directly, instead of dealing with the session?

Yep!

> Also, is that assignment of current_user something you also write yourself in the actual codebase, which is why you can just basically fake it during test?

Doorman only assigns `current_user` if it finds a user which is why you can assign it before an action is hit.
