### ISSUE TITLE
Case sensitivity?

### ISSUE THREAD

**Issue by drapergeek** [BlakeWilliams/doorman#22]
I just realized that doorman is enforcing case-sensitivity on my user's email even though I'm using a lowercase unique index. I can solve this in my app but I'm wondering if a PR to doorman would be preferred so that by default we query lowercase?

If you're up for it, I can have a PR in today.

**Comment by BlakeWilliams** [comment]
Definitely an oversight. I'd love a PR making it case insensitive.

**Comment by drapergeek** [comment]
Do you think it's reasonable to require that the user has lowered the emails before they went into the DB (or through a migration) or should we lower it on each query?  They could also use `citext` which is probably preferred.

If we preform a DB lower on each time but you've already lowered it seems like overkill. Also, if we have to lower the DB on each query using a fragment, we can't use our existing fakes and I'm fairly certain we'll have to add a real db to test things. By requiring your DB to store them lower, you're good to go and we can just downcase the email coming in. Easy peasy (lemon squeezy)

**Comment by BlakeWilliams** [comment]
> Do you think it's reasonable to require that the user has lowered the emails before they went into the DB (or through a migration) or should we lower it on each query?

Definitely. I think it's probably worth recommending using `citext` on postgres in the README.
