### ISSUE TITLE
Release soon?

### ISSUE THREAD

**Issue by drapergeek** [BlakeWilliams/doorman#26]
Seems like a few things have changed without a release which lead to a bit of confusion about master vs release. Any chance you're looking to release soon?

**Comment by BlakeWilliams** [comment]
Great point, I haven't touched this repo in a while. I'll push out a new release in just a few.

**Comment by BlakeWilliams** [comment]
Just released 0.6.0.

Thanks for the headsup!

**Comment by drapergeek** [comment]
Thanks @BlakeWilliams!
