### ISSUE TITLE
Doorman v0.6.0 at hex doesn't include Secret module

### ISSUE THREAD

**Issue by dbernheisel** [BlakeWilliams/doorman#28]
When using doorman v0.6.0 (current version at hex) I run into this compile error when trying to use `put_session_secret` from Doorman.Auth.Secret.

```
** (CompileError) lib/exgradebook/users/models/student.ex:5: module Doorman.Auth.Secret is not loaded and could not be found
```

When I use the master branch, all's good and the module is present.
Any chance for a release to hex that includes the module?

**Comment by BlakeWilliams** [comment]
I missed this issue, sorry.

I just pushed up v0.6.2 which should fix it. If not feel free to re-open.
